// src/data/quotes.js
export const quotes = [
    { content: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
    { content: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", author: "Ralph Waldo Emerson" },
    { content: "In the end, we will remember not the words of our enemies, but the silence of our friends.", author: "Martin Luther King Jr." },
    { content: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
    { content: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { content: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { content: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    { content: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { content: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein" },
    { content: "The best way to predict your future is to create it.", author: "Abraham Lincoln" },
    { content: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { content: "Everything you can imagine is real.", author: "Pablo Picasso" },
    { content: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    { content: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
    { content: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { content: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
    { content: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
    { content: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { content: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
    { content: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { content: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { content: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
    { content: "Act as if what you do makes a difference. It does.", author: "William James" },
    { content: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    { content: "The best way to predict the future is to invent it.", author: "Alan Kay" },
    { content: "Do what you can with all you have, wherever you are.", author: "Theodore Roosevelt" },
    { content: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt" },
    { content: "The mind is everything. What you think you become.", author: "Buddha" },
    { content: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { content: "Don’t wait for opportunity. Create it.", author: "Anonymous" },
    { content: "What we think, we become.", author: "Buddha" },
    { content: "To live a creative life, we must lose our fear of being wrong.", author: "Joseph Chilton Pearce" },
    { content: "Life isn’t about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
    { content: "Everything has beauty, but not everyone sees it.", author: "Confucius" },
    { content: "Success is not the absence of failure; it’s the persistence through failure.", author: "Aisha Tyler" },
    { content: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
    { content: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { content: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Anonymous" },
    { content: "You are braver than you believe, stronger than you seem, and smarter than you think.", author: "A.A. Milne" },
    { content: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
    { content: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { content: "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
    { content: "The best revenge is massive success.", author: "Frank Sinatra" },
    { content: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
    { content: "Two things are infinite: the universe and human stupidity; and I’m not sure about the universe.", author: "Albert Einstein" },
    { content: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
    { content: "In three words I can sum up everything I’ve learned about life: It goes on.", author: "Robert Frost" },
    { content: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
    { content: "Good things come to those who wait, but better things come to those who go out and get them.", author: "Anonymous" },
    { content: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { content: "Do what you love and you’ll never work a day in your life.", author: "Confucius" },
    { content: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
    { content: "When one door of happiness closes, another opens.", author: "Helen Keller" },
    { content: "You only live once, but if you do it right, once is enough.", author: "Mae West" }
  ];
  